"""
brain_of_the_doctor.py

Uses Groq Llama to explain the prediction generated by the
EfficientNet Skin Disease Classifier.

The LLM DOES NOT diagnose the image.
It only explains the classifier's prediction.
"""

import os
from dotenv import load_dotenv
from groq import Groq

# Load Environment Variables

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if GROQ_API_KEY is None:
    raise ValueError("GROQ_API_KEY not found in .env file")

client = Groq(api_key=GROQ_API_KEY)

# LLM Model

MODEL_NAME = "meta-llama/llama-4-scout-17b-16e-instruct"

# Generate Medical Explanation

def generate_medical_response(
    disease,
    confidence,
    patient_question
):
    """
    Generates a medical explanation using the
    classifier prediction.

    Parameters
    ----------
    disease : str
        Predicted skin disease.

    confidence : float
        Prediction confidence.

    patient_question : str
        User's spoken question.

    Returns
    -------
    str
        AI-generated medical response.
    """

    system_prompt = f"""
You are an experienced dermatologist.

A deep learning skin disease classifier has already analyzed the image.

Prediction:
{disease}

Confidence:
{confidence:.2f}%

Patient Question:
{patient_question}

Your job is NOT to diagnose the image again.

Instead:

• Explain what {disease} is.
• Mention common symptoms.
• Mention possible causes.
• Suggest general home care.
• Mention when a dermatologist should be consulted.
• If the confidence is below 70%, mention that the prediction is uncertain.
• Always remind the patient that this AI assistant cannot replace a medical professional.

Keep the answer concise (150-200 words).

Do not use markdown.

Respond naturally like a real doctor.
"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": system_prompt
            }
        ],
        temperature=0.3,
        max_tokens=350
    )

    return response.choices[0].message.content.strip()


# Testing

if __name__ == "__main__":

    reply = generate_medical_response(
        disease="Eczema",
        confidence=94.25,
        patient_question="How can I treat it at home?"
    )

    print(reply)